const now = () => new Date().toISOString()

export const mockDb = {
  products: [
    {
      id: 1,
      name: '社团文化衫',
      category: '服饰',
      type: 'tshirt',
      spec: 'S-XXL',
      price: 59,
      stock: 80,
      soldQty: 40,
      reservedQty: 8,
      customRule: '支持上传 PNG/PDF 设计稿',
      coverUrl: '',
      status: 'online',
      version: 1,
      updatedAt: now(),
    },
    {
      id: 2,
      name: '纪念徽章',
      category: '周边',
      type: 'badge',
      spec: '5cm',
      price: 12,
      stock: 240,
      soldQty: 120,
      reservedQty: 20,
      customRule: '支持 AI/PSD',
      coverUrl: '',
      status: 'online',
      version: 1,
      updatedAt: now(),
    },
    {
      id: 3,
      name: '活动笔记本',
      category: '文具',
      type: 'notebook',
      spec: 'A5',
      price: 26,
      stock: 120,
      soldQty: 34,
      reservedQty: 4,
      customRule: '支持封面定制',
      coverUrl: '',
      status: 'online',
      version: 1,
      updatedAt: now(),
    },
    {
      id: 4,
      name: '校庆鸭舌帽',
      category: '服饰',
      type: 'cap',
      spec: '可调节帽围',
      price: 39,
      stock: 96,
      soldQty: 21,
      reservedQty: 6,
      customRule: '支持前片刺绣',
      coverUrl: '',
      status: 'online',
      version: 1,
      updatedAt: now(),
    },
    {
      id: 5,
      name: '社团连帽卫衣',
      category: '服饰',
      type: 'hoodie',
      spec: 'M-3XL',
      price: 129,
      stock: 58,
      soldQty: 18,
      reservedQty: 10,
      customRule: '支持双面印花',
      coverUrl: '',
      status: 'online',
      version: 1,
      updatedAt: now(),
    },
    {
      id: 6,
      name: '亚克力立牌',
      category: '周边',
      type: 'standee',
      spec: '12cm',
      price: 25,
      stock: 180,
      soldQty: 73,
      reservedQty: 16,
      customRule: '支持透明底与异形切割',
      coverUrl: '',
      status: 'online',
      version: 1,
      updatedAt: now(),
    },
    {
      id: 7,
      name: '校训帆布笔袋',
      category: '文具',
      type: 'pencilcase',
      spec: '20x8cm',
      price: 22,
      stock: 140,
      soldQty: 52,
      reservedQty: 9,
      customRule: '支持单色丝印',
      coverUrl: '',
      status: 'online',
      version: 1,
      updatedAt: now(),
    },
    {
      id: 8,
      name: '活动工作证挂绳',
      category: '周边',
      type: 'lanyard',
      spec: '90cm',
      price: 9,
      stock: 420,
      soldQty: 130,
      reservedQty: 24,
      customRule: '支持LOGO重复排版',
      coverUrl: '',
      status: 'online',
      version: 1,
      updatedAt: now(),
    },
    {
      id: 9,
      name: '校园纪念马克杯',
      category: '周边',
      type: 'mug',
      spec: '350ml',
      price: 36,
      stock: 88,
      soldQty: 37,
      reservedQty: 7,
      customRule: '支持热转印彩色图案',
      coverUrl: '',
      status: 'offline',
      version: 1,
      updatedAt: now(),
    },
    {
      id: 10,
      name: '学院主题便签本',
      category: '文具',
      type: 'memo',
      spec: '80页',
      price: 14,
      stock: 210,
      soldQty: 66,
      reservedQty: 12,
      customRule: '支持封面主题可选',
      coverUrl: '',
      status: 'online',
      version: 1,
      updatedAt: now(),
    },
  ],
  orders: [
    {
      id: 'ORD-20260401',
      productId: 1,
      productName: '社团文化衫',
      quantity: 12,
      preference: 'M码 深蓝',
      remark: '社团活动统一服装',
      status: 'design_pending',
      designUrl: '',
      userId: 'u1001',
      userName: 'demo',
      createdAt: now(),
    },
    {
      id: 'ORD-20260418',
      productId: 2,
      productName: '纪念徽章',
      quantity: 60,
      preference: '银色',
      remark: '',
      status: 'ready',
      designUrl: '',
      userId: 'u1001',
      userName: 'demo',
      createdAt: now(),
    },
    {
      id: 'ORD-20260423',
      productId: 3,
      productName: '活动笔记本',
      quantity: 30,
      preference: '米白封面',
      remark: '',
      status: 'completed',
      designUrl: '',
      userId: 'u1001',
      userName: 'demo',
      createdAt: now(),
    },
  ],
  auditLogs: [],
}

export const nextProductId = () =>
  (mockDb.products.at(-1)?.id ? Number(mockDb.products.at(-1).id) : 0) + 1
